# 使用官方 Go 镜像作为基础镜像
FROM golang:1.20 AS builder

# 设置工作目录
WORKDIR /app

# 复制 go.mod 和 go.sum 文件
COPY . .

# 下载依赖
RUN go mod download


# 编译 Go 应用
RUN go build -o myapp main.go

# 使用较小的基础镜像来运行应用
FROM alpine:latest

# 设置工作目录
WORKDIR /root/

# 从 builder 阶段复制编译好的二进制文件
COPY --from=builder /app/myapp .

# 暴露应用的监听端口
EXPOSE 11000

# 运行应用
CMD ["./myapp"]
